version: "2"
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./mongo/mongo.conf:/etc/mongo.conf
    command: "mongod --config /etc/mongo.conf"
  redis:
    image: redis:latest
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
